import { getSessionData } from "./(lib)/session";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const sessionData = await getSessionData();

  return (
    <html lang="en">
      <body>
        {children}
        <div>{sessionData ? sessionData.characterId : "not connected"}</div>
      </body>
    </html>
  );
}
